### ISSUE TITLE
UUID skin requests

### ISSUE THREAD

**Issue by South-Paw** [TehRainbowGuy/JPixelFace#1]
Would it be possible to get skins by UUID as well as username?

https://PixelFace.net/avatar/[Name]/[Size] OR https://PixelFace.net/avatar/[UUID]/[Size]

Now that Minecraft name changing is available on account.mojang.com, players are changing their names and skins are not loading (because that username doesn't go to a UUID anymore)

**Comment by TehRainbowGuy** [comment]
Hi there,

I will look into adding full uuid support later today, in the mean time you
should be able to use mojang style uuids (Just remove the dashes.)

**Comment by TehRainbowGuy** [comment]
Patch deployed to production

**Comment by South-Paw** [comment]
Thanks! Much appreciated :)

**Comment by TehRainbowGuy** [comment]
No problem!
